use super::env_checker::EnvConflict;
use chrono::Utc;
use serde::{Deserialize, Serialize};
#[cfg(target_os = "windows")]
use std::ffi::c_void;
use std::fs;
use std::path::PathBuf;

#[cfg(target_os = "windows")]
use winreg::enums::*;
#[cfg(target_os = "windows")]
use winreg::RegKey;

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BackupInfo {
    pub backup_path: String,
    pub timestamp: String,
    pub conflicts: Vec<EnvConflict>,
}

#[cfg(target_os = "windows")]
pub fn get_user_env_var(name: &str) -> Result<Option<String>, String> {
    let hkcu = RegKey::predef(HKEY_CURRENT_USER)
        .open_subkey("Environment")
        .map_err(|e| format!("打开用户环境变量注册表失败: {e}"))?;

    match hkcu.get_value::<String, _>(name) {
        Ok(value) => Ok(Some(value)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(format!("读取用户环境变量失败: {err}")),
    }
}

#[cfg(not(target_os = "windows"))]
pub fn get_user_env_var(name: &str) -> Result<Option<String>, String> {
    if let Ok(value) = std::env::var(name) {
        return Ok(Some(value));
    }

    get_persisted_unix_user_env_var(name)
}

#[cfg(target_os = "windows")]
pub fn set_user_env_var(name: &str, value: Option<&str>) -> Result<(), String> {
    set_user_env_var_with_notifier(name, value, notify_windows_environment_changed)
}

#[cfg(target_os = "windows")]
fn set_user_env_var_with_notifier<F>(
    name: &str,
    value: Option<&str>,
    notify: F,
) -> Result<(), String>
where
    F: Fn() -> Result<(), String>,
{
    let (hkcu, _) = RegKey::predef(HKEY_CURRENT_USER)
        .create_subkey("Environment")
        .map_err(|e| format!("打开用户环境变量注册表失败: {e}"))?;

    match value.map(str::trim).filter(|value| !value.is_empty()) {
        Some(next) => hkcu
            .set_value(name, &next)
            .map_err(|e| format!("写入用户环境变量失败: {e}"))?,
        None => {
            let _ = hkcu.delete_value(name);
        }
    }

    notify()?;

    Ok(())
}

#[cfg(target_os = "windows")]
fn notify_windows_environment_changed() -> Result<(), String> {
    const HWND_BROADCAST: *mut c_void = 0xffffusize as *mut c_void;
    const WM_SETTINGCHANGE: u32 = 0x001A;
    const SMTO_ABORTIFHUNG: u32 = 0x0002;

    unsafe extern "system" {
        fn SendMessageTimeoutW(
            h_wnd: *mut c_void,
            msg: u32,
            w_param: usize,
            l_param: *const u16,
            flags: u32,
            timeout: u32,
            result: *mut usize,
        ) -> isize;
    }

    let environment: Vec<u16> = "Environment\0".encode_utf16().collect();
    let status = unsafe {
        SendMessageTimeoutW(
            HWND_BROADCAST,
            WM_SETTINGCHANGE,
            0,
            environment.as_ptr(),
            SMTO_ABORTIFHUNG,
            5000,
            std::ptr::null_mut(),
        )
    };

    if status == 0 {
        return Err(format!(
            "通知 Windows 刷新环境变量失败: {}",
            std::io::Error::last_os_error()
        ));
    }

    Ok(())
}

#[cfg(not(target_os = "windows"))]
pub fn set_user_env_var(name: &str, value: Option<&str>) -> Result<(), String> {
    match value.map(str::trim).filter(|value| !value.is_empty()) {
        Some(next) => {
            std::env::set_var(name, next);
            persist_unix_user_env_var(name, Some(next))?;
        }
        None => {
            std::env::remove_var(name);
            persist_unix_user_env_var(name, None)?;
        }
    }
    Ok(())
}

#[cfg(any(not(target_os = "windows"), test))]
const UNIX_ENV_HEADER: &str =
    "# Generated by CC Switch. Sourced by shell startup files for persisted CLI env.\n";
#[cfg(any(not(target_os = "windows"), test))]
const UNIX_SHELL_SOURCE_LINE: &str =
    "[ -f \"$HOME/.cc-switch/env.sh\" ] && . \"$HOME/.cc-switch/env.sh\" # cc-switch env";

#[cfg(not(target_os = "windows"))]
fn persist_unix_user_env_var(name: &str, value: Option<&str>) -> Result<(), String> {
    if !is_valid_env_name(name) {
        return Err(format!("Invalid environment variable name: {name}"));
    }

    let home = crate::config::get_home_dir();
    let env_dir = home.join(".cc-switch");
    fs::create_dir_all(&env_dir)
        .map_err(|e| format!("创建 Unix 用户环境变量目录失败 {}: {e}", env_dir.display()))?;

    let env_file = env_dir.join("env.sh");
    let current = match fs::read_to_string(&env_file) {
        Ok(current) => current,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(err) => {
            return Err(format!(
                "读取 Unix 用户环境变量文件失败 {}: {err}",
                env_file.display()
            ))
        }
    };
    fs::write(
        &env_file,
        upsert_unix_env_file_content(&current, name, value),
    )
    .map_err(|e| format!("写入 Unix 用户环境变量文件失败 {}: {e}", env_file.display()))?;

    ensure_unix_shell_startup_sources_env(&home)
}

#[cfg(not(target_os = "windows"))]
fn ensure_unix_shell_startup_sources_env(home: &std::path::Path) -> Result<(), String> {
    for rc_name in [".profile", ".bashrc", ".zshrc"] {
        let path = home.join(rc_name);
        let current = match fs::read_to_string(&path) {
            Ok(current) => current,
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => String::new(),
            Err(err) => {
                return Err(format!(
                    "读取 Unix shell 启动文件失败 {}: {err}",
                    path.display()
                ))
            }
        };
        if current.contains("# cc-switch env") || current.contains(".cc-switch/env.sh") {
            continue;
        }

        let mut next = current;
        if !next.is_empty() && !next.ends_with('\n') {
            next.push('\n');
        }
        next.push_str(UNIX_SHELL_SOURCE_LINE);
        next.push('\n');
        fs::write(&path, next)
            .map_err(|e| format!("更新 Unix shell 启动文件失败 {}: {e}", path.display()))?;
    }

    Ok(())
}

#[cfg(not(target_os = "windows"))]
fn get_persisted_unix_user_env_var(name: &str) -> Result<Option<String>, String> {
    if !is_valid_env_name(name) {
        return Err(format!("Invalid environment variable name: {name}"));
    }

    let env_file = crate::config::get_home_dir()
        .join(".cc-switch")
        .join("env.sh");
    let content = match fs::read_to_string(&env_file) {
        Ok(content) => content,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => {
            return Err(format!(
                "读取 Unix 用户环境变量文件失败 {}: {err}",
                env_file.display()
            ))
        }
    };

    Ok(parse_unix_env_file_var(&content, name))
}

#[cfg(not(target_os = "windows"))]
fn parse_unix_env_file_var(content: &str, name: &str) -> Option<String> {
    let export_prefix = format!("export {name}=");
    let unset_line = format!("unset {name}");
    let mut current = None;

    for line in content.lines().map(str::trim) {
        if line == unset_line {
            current = None;
        } else if let Some(value) = line.strip_prefix(&export_prefix) {
            current = Some(parse_shell_single_quoted_value(value));
        }
    }

    current
}

#[cfg(not(target_os = "windows"))]
fn parse_shell_single_quoted_value(value: &str) -> String {
    if value.starts_with('\'') && value.ends_with('\'') && value.len() >= 2 {
        value[1..value.len() - 1].replace("'\\''", "'")
    } else {
        value.to_string()
    }
}

#[cfg(any(not(target_os = "windows"), test))]
fn upsert_unix_env_file_content(current: &str, name: &str, value: Option<&str>) -> String {
    let export_prefix = format!("export {name}=");
    let unset_line = format!("unset {name}");
    let mut lines: Vec<String> = current
        .lines()
        .filter(|line| !line.starts_with(&export_prefix) && *line != unset_line)
        .filter(|line| *line != UNIX_ENV_HEADER.trim_end())
        .map(ToString::to_string)
        .collect();

    match value {
        Some(value) => {
            lines.push(format!("export {name}={}", shell_single_quote(value)));
        }
        None => {
            lines.push(format!("unset {name}"));
        }
    }

    let mut content = UNIX_ENV_HEADER.to_string();
    if !lines.is_empty() {
        content.push_str(&lines.join("\n"));
        content.push('\n');
    }
    content
}

#[cfg(any(not(target_os = "windows"), test))]
fn shell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(any(not(target_os = "windows"), test))]
fn is_valid_env_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

/// Delete environment variables with automatic backup
pub fn delete_env_vars(conflicts: Vec<EnvConflict>) -> Result<BackupInfo, String> {
    // Step 1: Create backup
    let backup_info = create_backup(&conflicts)?;

    // Step 2: Delete variables
    for conflict in &conflicts {
        match delete_single_env(conflict) {
            Ok(_) => {}
            Err(e) => {
                // If deletion fails, we keep the backup but return error
                return Err(format!(
                    "删除环境变量失败: {}. 备份已保存到: {}",
                    e, backup_info.backup_path
                ));
            }
        }
    }

    Ok(backup_info)
}

/// Create backup file before deletion
fn create_backup(conflicts: &[EnvConflict]) -> Result<BackupInfo, String> {
    // Get backup directory
    let backup_dir = get_backup_dir()?;
    fs::create_dir_all(&backup_dir).map_err(|e| format!("创建备份目录失败: {e}"))?;

    // Generate backup file name with timestamp
    let timestamp = Utc::now().format("%Y%m%d_%H%M%S").to_string();
    let backup_file = backup_dir.join(format!("env-backup-{timestamp}.json"));

    // Create backup data
    let backup_info = BackupInfo {
        backup_path: backup_file.to_string_lossy().to_string(),
        timestamp: timestamp.clone(),
        conflicts: conflicts.to_vec(),
    };

    // Write backup file
    let json = serde_json::to_string_pretty(&backup_info)
        .map_err(|e| format!("序列化备份数据失败: {e}"))?;

    fs::write(&backup_file, json).map_err(|e| format!("写入备份文件失败: {e}"))?;

    Ok(backup_info)
}

/// Get backup directory path
fn get_backup_dir() -> Result<PathBuf, String> {
    let home = dirs::home_dir().ok_or("无法获取用户主目录")?;
    Ok(home.join(".cc-switch").join("backups"))
}

/// Delete a single environment variable
#[cfg(target_os = "windows")]
fn delete_single_env(conflict: &EnvConflict) -> Result<(), String> {
    match conflict.source_type.as_str() {
        "system" => {
            if conflict.source_path.contains("HKEY_CURRENT_USER") {
                let hkcu = RegKey::predef(HKEY_CURRENT_USER)
                    .open_subkey_with_flags("Environment", KEY_ALL_ACCESS)
                    .map_err(|e| format!("打开注册表失败: {}", e))?;

                hkcu.delete_value(&conflict.var_name)
                    .map_err(|e| format!("删除注册表项失败: {}", e))?;
            } else if conflict.source_path.contains("HKEY_LOCAL_MACHINE") {
                let hklm = RegKey::predef(HKEY_LOCAL_MACHINE)
                    .open_subkey_with_flags(
                        "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment",
                        KEY_ALL_ACCESS,
                    )
                    .map_err(|e| format!("打开系统注册表失败 (需要管理员权限): {}", e))?;

                hklm.delete_value(&conflict.var_name)
                    .map_err(|e| format!("删除系统注册表项失败: {}", e))?;
            }
            Ok(())
        }
        "file" => Err("Windows 系统不应该有文件类型的环境变量".to_string()),
        _ => Err(format!("未知的环境变量来源类型: {}", conflict.source_type)),
    }
}

#[cfg(not(target_os = "windows"))]
fn delete_single_env(conflict: &EnvConflict) -> Result<(), String> {
    match conflict.source_type.as_str() {
        "file" => {
            // Parse file path and line number from source_path (format: "path:line")
            let parts: Vec<&str> = conflict.source_path.split(':').collect();
            if parts.len() < 2 {
                return Err("无效的文件路径格式".to_string());
            }

            let file_path = parts[0];

            // Read file content
            let content = fs::read_to_string(file_path)
                .map_err(|e| format!("读取文件失败 {file_path}: {e}"))?;

            // Filter out the line containing the environment variable
            let new_content: Vec<String> = content
                .lines()
                .filter(|line| {
                    let trimmed = line.trim();
                    let export_line = trimmed.strip_prefix("export ").unwrap_or(trimmed);

                    // Check if this line sets the target variable
                    if let Some(eq_pos) = export_line.find('=') {
                        let var_name = export_line[..eq_pos].trim();
                        var_name != conflict.var_name
                    } else {
                        true
                    }
                })
                .map(|s| s.to_string())
                .collect();

            // Write back to file
            fs::write(file_path, new_content.join("\n"))
                .map_err(|e| format!("写入文件失败 {file_path}: {e}"))?;

            Ok(())
        }
        "system" => {
            // On Unix, we can't directly delete process environment variables
            Ok(())
        }
        _ => Err(format!("未知的环境变量来源类型: {}", conflict.source_type)),
    }
}

/// Restore environment variables from backup
pub fn restore_from_backup(backup_path: String) -> Result<(), String> {
    // Read backup file
    let content = fs::read_to_string(&backup_path).map_err(|e| format!("读取备份文件失败: {e}"))?;

    let backup_info: BackupInfo =
        serde_json::from_str(&content).map_err(|e| format!("解析备份文件失败: {e}"))?;

    // Restore each variable
    for conflict in &backup_info.conflicts {
        restore_single_env(conflict)?;
    }

    Ok(())
}

/// Restore a single environment variable
#[cfg(target_os = "windows")]
fn restore_single_env(conflict: &EnvConflict) -> Result<(), String> {
    match conflict.source_type.as_str() {
        "system" => {
            if conflict.source_path.contains("HKEY_CURRENT_USER") {
                let (hkcu, _) = RegKey::predef(HKEY_CURRENT_USER)
                    .create_subkey("Environment")
                    .map_err(|e| format!("打开注册表失败: {}", e))?;

                hkcu.set_value(&conflict.var_name, &conflict.var_value)
                    .map_err(|e| format!("恢复注册表项失败: {}", e))?;
            } else if conflict.source_path.contains("HKEY_LOCAL_MACHINE") {
                let (hklm, _) = RegKey::predef(HKEY_LOCAL_MACHINE)
                    .create_subkey(
                        "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment",
                    )
                    .map_err(|e| format!("打开系统注册表失败 (需要管理员权限): {}", e))?;

                hklm.set_value(&conflict.var_name, &conflict.var_value)
                    .map_err(|e| format!("恢复系统注册表项失败: {}", e))?;
            }
            Ok(())
        }
        _ => Err(format!(
            "无法恢复类型为 {} 的环境变量",
            conflict.source_type
        )),
    }
}

#[cfg(not(target_os = "windows"))]
fn restore_single_env(conflict: &EnvConflict) -> Result<(), String> {
    match conflict.source_type.as_str() {
        "file" => {
            // Parse file path from source_path
            let parts: Vec<&str> = conflict.source_path.split(':').collect();
            if parts.is_empty() {
                return Err("无效的文件路径格式".to_string());
            }

            let file_path = parts[0];

            // Read file content
            let mut content = fs::read_to_string(file_path)
                .map_err(|e| format!("读取文件失败 {file_path}: {e}"))?;

            // Append the environment variable line
            let export_line = format!("\nexport {}={}", conflict.var_name, conflict.var_value);
            content.push_str(&export_line);

            // Write back to file
            fs::write(file_path, content).map_err(|e| format!("写入文件失败 {file_path}: {e}"))?;

            Ok(())
        }
        _ => Err(format!(
            "无法恢复类型为 {} 的环境变量",
            conflict.source_type
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(not(target_os = "windows"))]
    use serial_test::serial;

    #[cfg(not(target_os = "windows"))]
    struct TestEnvGuard {
        old_test_home: Option<std::ffi::OsString>,
        old_var: Option<std::ffi::OsString>,
        name: &'static str,
    }

    #[cfg(not(target_os = "windows"))]
    impl TestEnvGuard {
        fn new(home: &std::path::Path, name: &'static str) -> Self {
            let guard = Self {
                old_test_home: std::env::var_os("CC_SWITCH_TEST_HOME"),
                old_var: std::env::var_os(name),
                name,
            };
            std::env::set_var("CC_SWITCH_TEST_HOME", home);
            guard
        }
    }

    #[cfg(not(target_os = "windows"))]
    impl Drop for TestEnvGuard {
        fn drop(&mut self) {
            match &self.old_test_home {
                Some(value) => std::env::set_var("CC_SWITCH_TEST_HOME", value),
                None => std::env::remove_var("CC_SWITCH_TEST_HOME"),
            }
            match &self.old_var {
                Some(value) => std::env::set_var(self.name, value),
                None => std::env::remove_var(self.name),
            }
        }
    }

    #[test]
    fn test_backup_dir_creation() {
        let backup_dir = get_backup_dir();
        assert!(backup_dir.is_ok());
    }

    #[cfg(target_os = "windows")]
    #[test]
    fn set_user_env_var_notifies_windows_after_registry_update() {
        use std::sync::{
            atomic::{AtomicUsize, Ordering},
            Arc,
        };

        let name = "CC_SWITCH_TEST_NOTIFY_ENV";
        let notify_calls = Arc::new(AtomicUsize::new(0));
        let notify_calls_for_set = Arc::clone(&notify_calls);

        set_user_env_var_with_notifier(name, Some("value"), move || {
            notify_calls_for_set.fetch_add(1, Ordering::SeqCst);
            Ok(())
        })
        .expect("set env var");

        assert_eq!(
            notify_calls.load(Ordering::SeqCst),
            1,
            "set path should notify Windows environment change"
        );

        let notify_calls_for_delete = Arc::clone(&notify_calls);
        set_user_env_var_with_notifier(name, None, move || {
            notify_calls_for_delete.fetch_add(1, Ordering::SeqCst);
            Ok(())
        })
        .expect("delete env var");

        assert_eq!(
            notify_calls.load(Ordering::SeqCst),
            2,
            "delete path should notify Windows environment change"
        );
    }

    #[test]
    fn unix_env_file_content_upserts_and_shell_quotes_values() {
        let content = upsert_unix_env_file_content(
            "export CC_SWITCH_KEEP='old'\nexport CC_SWITCH_TEST_UNIX_ENV='old'\n",
            "CC_SWITCH_TEST_UNIX_ENV",
            Some("/tmp/claude profile's dir"),
        );

        assert!(content.contains("export CC_SWITCH_KEEP='old'"));
        assert!(content.contains("export CC_SWITCH_TEST_UNIX_ENV='/tmp/claude profile'\\''s dir'"));

        let content = upsert_unix_env_file_content(&content, "CC_SWITCH_TEST_UNIX_ENV", None);
        assert!(content.contains("export CC_SWITCH_KEEP='old'"));
        assert!(!content.contains("export CC_SWITCH_TEST_UNIX_ENV="));
        assert!(content.contains("unset CC_SWITCH_TEST_UNIX_ENV"));
    }

    #[cfg(not(target_os = "windows"))]
    #[test]
    #[serial]
    fn set_user_env_var_persists_unix_shell_env_file() {
        let temp_home = tempfile::tempdir().expect("temp home");
        let name = "CC_SWITCH_TEST_UNIX_ENV";
        let _env = TestEnvGuard::new(temp_home.path(), name);

        set_user_env_var(name, Some("  /tmp/claude profile  ")).expect("persist unix user env var");

        let env_file = temp_home.path().join(".cc-switch").join("env.sh");
        let content = fs::read_to_string(&env_file).expect("read unix env file");
        assert!(
            content.contains("export CC_SWITCH_TEST_UNIX_ENV='/tmp/claude profile'"),
            "unix user env file should contain a shell-escaped export"
        );

        set_user_env_var(name, None).expect("remove unix user env var");
        let content = fs::read_to_string(&env_file).expect("read unix env file after removal");
        assert!(
            !content.contains("export CC_SWITCH_TEST_UNIX_ENV="),
            "removing the env var should remove the export line"
        );
        assert!(
            content.contains("unset CC_SWITCH_TEST_UNIX_ENV"),
            "removing the env var should write an unset line"
        );
    }

    #[cfg(not(target_os = "windows"))]
    #[test]
    #[serial]
    fn get_user_env_var_reads_persisted_unix_shell_env_file() {
        let temp_home = tempfile::tempdir().expect("temp home");
        let name = "CC_SWITCH_TEST_UNIX_ENV";
        let _env = TestEnvGuard::new(temp_home.path(), name);

        set_user_env_var(name, Some("  /tmp/claude profile's dir  "))
            .expect("persist unix user env var");
        std::env::remove_var(name);

        assert_eq!(
            get_user_env_var(name)
                .expect("read persisted unix user env var")
                .as_deref(),
            Some("/tmp/claude profile's dir"),
            "unix user env lookup should fall back to the persisted env file"
        );
    }

    #[cfg(not(target_os = "windows"))]
    #[test]
    #[serial]
    fn set_user_env_var_preserves_undecodable_unix_rc_files() {
        let temp_home = tempfile::tempdir().expect("temp home");
        let name = "CC_SWITCH_TEST_UNIX_ENV";
        let _env = TestEnvGuard::new(temp_home.path(), name);

        let rc_path = temp_home.path().join(".profile");
        let original = vec![
            0xff, b'e', b'x', b'p', b'o', b'r', b't', b' ', b'O', b'L', b'D',
        ];
        fs::write(&rc_path, &original).expect("seed undecodable rc file");

        let err = set_user_env_var(name, Some("/tmp/claude"))
            .expect_err("undecodable rc file should abort startup source update");
        assert!(
            err.contains("读取 Unix shell 启动文件失败"),
            "expected rc read failure, got {err}"
        );
        assert_eq!(
            fs::read(&rc_path).expect("read rc file bytes"),
            original,
            "undecodable rc file should remain byte-for-byte unchanged"
        );
    }
}
